Importer la base de donnée avec ces 2 tutos (FR ou En)
FR
https://www.tresfacile.net/python-et-les-bases-de-donnees-sqlite3/

EN
https://likegeeks.com/python-sqlite3-tutorial/

In [1]:
import sqlite3 as sq3

In [2]:
conn = sq3.connect("./Fifa19.db") # Crée une connexion  vers la database. Dans notre cas la database est locale.
 # N.B : Si la 
conn?

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute("select*from fifa19")

OperationalError: no such table: fifa19

Avant cette requête ne fonctionnait pas. On avait un message qui disait qu'on est limité.

In [5]:
import pandas as pd # J'ai besoin de pandas pour travailler avec des dataframe. Je l'importe
cursor.execute("select*from fifa19 limit 500") # J'utilise le cursor pour executer la requête SQL
split1 = pd.DataFrame(cursor.fetchall()) # Je peux récupérer le résultat avec la fonction fetchall() du cursor
split1 # J'affiche mon nouveau dataframe.

OperationalError: no such table: fifa19

In [ ]:
# pour la deuxième partie, je fais la même chose en économisant quelques lignes.
split2 = cursor.execute("select*from fifa19 limit 500 Offset 500")
split2

Maintenant je doit réunir mes deux tableaux pour n'en faire qu'un seul. Je pourrait donc commencer mes visualisation des données.


Je voulais montrer pourquoi on avait split la db en 2 (Car on était limité en taille)  mais on s'est rendu compte que maintenant on pouvait importer toute la base d'un coup.

In [43]:
import pandas as pd
cursor.execute("select*from fifa19")
dfTotal = pd.DataFrame(cursor.fetchall())
print(cursor.fetchall)
cursor.fetchall

<built-in method fetchall of sqlite3.Cursor object at 0x000001B96BBB6D50>

In [44]:
dfTotal

,0,1,2,3,4,5,6,7,8,9,...,79,80,81,82,83,84,85,86,87,88
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96,33,28,26,6,11,15,14,8,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95,28,31,23,7,11,15,14,11,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94,27,24,33,9,9,15,15,11,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68,15,21,13,90,85,87,88,94,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88,68,58,51,15,13,5,10,13,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45,40,48,47,10,13,7,8,9,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42,22,15,19,10,9,9,5,12,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41,32,13,11,6,5,10,6,13,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46,20,25,27,14,6,14,8,9,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43,40,43,50,10,15,9,12,9,€165K

Je vais donc pouvoir travailler à visionner les données

In [51]:
import seaborn as sns
print(dfTotal.dtypes)
liste = dfTotal.dtypes

0     object
1     object
2     object
3     object
4     object
       ...
84    object
85    object
86    object
87    object
88    object
Length: 89, dtype: object

0     object
1     object
2     object
3     object
4     object
       ...
84    object
85    object
86    object
87    object
88    object
Length: 89, dtype: object